# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\freecad-8-26-all-success\Mod\Muffler\MufflerData\views\MufflerDataPanel.ui'
#
# Created: Fri Mar 06 11:16:40 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MufflerDataPanel(object):
    def setupUi(self, MufflerDataPanel):
        MufflerDataPanel.setObjectName(_fromUtf8("MufflerDataPanel"))
        MufflerDataPanel.resize(380, 443)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MufflerDataPanel.sizePolicy().hasHeightForWidth())
        MufflerDataPanel.setSizePolicy(sizePolicy)
        MufflerDataPanel.setMinimumSize(QtCore.QSize(380, 440))
        MufflerDataPanel.setMaximumSize(QtCore.QSize(380, 16777215))
        self.tabWidget = QtGui.QTabWidget(MufflerDataPanel)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 361, 391))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(30, 40, 231, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(0, _fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox2 = QtGui.QComboBox(self.tab)
        self.comboBox2.setGeometry(QtCore.QRect(58, 80, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox2.setFont(font)
        self.comboBox2.setObjectName(_fromUtf8("comboBox2"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(180, 80, 16, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(186, 80, 166, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.comboBox5 = QtGui.QComboBox(self.tab)
        self.comboBox5.setGeometry(QtCore.QRect(0, 110, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox5.setFont(font)
        self.comboBox5.setObjectName(_fromUtf8("comboBox5"))
        self.comboBox5.addItem(_fromUtf8(""))
        self.comboBox5.addItem(_fromUtf8(""))
        self.comboBox3 = QtGui.QComboBox(self.tab)
        self.comboBox3.setGeometry(QtCore.QRect(58, 110, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox3.setFont(font)
        self.comboBox3.setObjectName(_fromUtf8("comboBox3"))
        self.lineEdit2 = QtGui.QLineEdit(self.tab)
        self.lineEdit2.setGeometry(QtCore.QRect(186, 110, 166, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setObjectName(_fromUtf8("lineEdit2"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(180, 110, 16, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox6 = QtGui.QComboBox(self.tab)
        self.comboBox6.setGeometry(QtCore.QRect(0, 140, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox6.setFont(font)
        self.comboBox6.setObjectName(_fromUtf8("comboBox6"))
        self.comboBox6.addItem(_fromUtf8(""))
        self.comboBox6.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(180, 140, 16, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit3 = QtGui.QLineEdit(self.tab)
        self.lineEdit3.setGeometry(QtCore.QRect(186, 140, 166, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setObjectName(_fromUtf8("lineEdit3"))
        self.comboBox4 = QtGui.QComboBox(self.tab)
        self.comboBox4.setGeometry(QtCore.QRect(58, 140, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox4.setFont(font)
        self.comboBox4.setObjectName(_fromUtf8("comboBox4"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(170, 180, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 180, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.treeView = QtGui.QTreeView(self.tab_2)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 361, 331))
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_2)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 340, 75, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 340, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(MufflerDataPanel)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MufflerDataPanel)

    def retranslateUi(self, MufflerDataPanel):
        MufflerDataPanel.setWindowTitle(_translate("MufflerDataPanel", "MufflerData", None))
        self.label.setText(_translate("MufflerDataPanel", "选择需要查询的内容", None))
        self.comboBox.setItemText(1, _translate("MufflerDataPanel", "项目信息", None))
        self.comboBox.setItemText(2, _translate("MufflerDataPanel", "子方案信息", None))
        self.comboBox.setItemText(3, _translate("MufflerDataPanel", "消声器信息", None))
        self.comboBox.setItemText(4, _translate("MufflerDataPanel", "车型信息", None))
        self.comboBox.setItemText(5, _translate("MufflerDataPanel", "发动机信息", None))
        self.comboBox.setItemText(6, _translate("MufflerDataPanel", "排气歧管信息", None))
        self.comboBox.setItemText(7, _translate("MufflerDataPanel", "催化器信息", None))
        self.label_2.setText(_translate("MufflerDataPanel", "=", None))
        self.comboBox5.setItemText(0, _translate("MufflerDataPanel", "AND", None))
        self.comboBox5.setItemText(1, _translate("MufflerDataPanel", "OR", None))
        self.label_5.setText(_translate("MufflerDataPanel", "=", None))
        self.comboBox6.setItemText(0, _translate("MufflerDataPanel", "AND", None))
        self.comboBox6.setItemText(1, _translate("MufflerDataPanel", "OR", None))
        self.label_6.setText(_translate("MufflerDataPanel", "=", None))
        self.pushButton.setText(_translate("MufflerDataPanel", "查询", None))
        self.pushButton_3.setText(_translate("MufflerDataPanel", "添加", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MufflerDataPanel", "查询操作", None))
        self.pushButton_5.setText(_translate("MufflerDataPanel", "删除", None))
        self.pushButton_4.setText(_translate("MufflerDataPanel", "添加", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MufflerDataPanel", "项目显示", None))

