# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\freecad-8-26-all-success\Mod\Database\MufflerData\views\MufflerPanel_Para_4_MotoType_Add.ui'
#
# Created: Wed Feb 25 11:23:35 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Para_MotoType_Add_Dlg(object):
    def setupUi(self, Para_MotoType_Add_Dlg):
        Para_MotoType_Add_Dlg.setObjectName(_fromUtf8("Para_MotoType_Add_Dlg"))
        Para_MotoType_Add_Dlg.resize(400, 450)
        Para_MotoType_Add_Dlg.setMinimumSize(QtCore.QSize(400, 450))
        Para_MotoType_Add_Dlg.setMaximumSize(QtCore.QSize(400, 450))
        Para_MotoType_Add_Dlg.setModal(False)
        self.lineEdit1 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit1.setEnabled(False)
        self.lineEdit1.setGeometry(QtCore.QRect(160, 20, 171, 20))
        self.lineEdit1.setObjectName(_fromUtf8("lineEdit1"))
        self.btn_ok = QtGui.QPushButton(Para_MotoType_Add_Dlg)
        self.btn_ok.setGeometry(QtCore.QRect(40, 400, 75, 23))
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.btn_cancel = QtGui.QPushButton(Para_MotoType_Add_Dlg)
        self.btn_cancel.setGeometry(QtCore.QRect(160, 400, 75, 23))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.label1 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label1.setGeometry(QtCore.QRect(70, 20, 81, 16))
        self.label1.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label1.setObjectName(_fromUtf8("label1"))
        self.lineEdit2 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit2.setGeometry(QtCore.QRect(160, 50, 171, 20))
        self.lineEdit2.setText(_fromUtf8(""))
        self.lineEdit2.setObjectName(_fromUtf8("lineEdit2"))
        self.label2 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label2.setGeometry(QtCore.QRect(70, 50, 81, 16))
        self.label2.setStyleSheet(_fromUtf8(""))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.lineEdit3 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit3.setGeometry(QtCore.QRect(160, 80, 171, 20))
        self.lineEdit3.setText(_fromUtf8(""))
        self.lineEdit3.setObjectName(_fromUtf8("lineEdit3"))
        self.label3 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label3.setGeometry(QtCore.QRect(70, 80, 81, 16))
        self.label3.setStyleSheet(_fromUtf8(""))
        self.label3.setObjectName(_fromUtf8("label3"))
        self.label4 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label4.setGeometry(QtCore.QRect(70, 110, 81, 16))
        self.label4.setStyleSheet(_fromUtf8(""))
        self.label4.setObjectName(_fromUtf8("label4"))
        self.lineEdit4 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit4.setGeometry(QtCore.QRect(160, 110, 171, 20))
        self.lineEdit4.setText(_fromUtf8(""))
        self.lineEdit4.setObjectName(_fromUtf8("lineEdit4"))
        self.label5 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label5.setGeometry(QtCore.QRect(70, 140, 81, 16))
        self.label5.setStyleSheet(_fromUtf8(""))
        self.label5.setObjectName(_fromUtf8("label5"))
        self.lineEdit5 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit5.setGeometry(QtCore.QRect(160, 140, 171, 20))
        self.lineEdit5.setText(_fromUtf8(""))
        self.lineEdit5.setObjectName(_fromUtf8("lineEdit5"))
        self.label6 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label6.setGeometry(QtCore.QRect(70, 170, 81, 16))
        self.label6.setStyleSheet(_fromUtf8(""))
        self.label6.setObjectName(_fromUtf8("label6"))
        self.lineEdit6 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit6.setGeometry(QtCore.QRect(160, 170, 171, 20))
        self.lineEdit6.setText(_fromUtf8(""))
        self.lineEdit6.setObjectName(_fromUtf8("lineEdit6"))
        self.label7 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label7.setGeometry(QtCore.QRect(70, 200, 81, 16))
        self.label7.setStyleSheet(_fromUtf8(""))
        self.label7.setObjectName(_fromUtf8("label7"))
        self.lineEdit7 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit7.setGeometry(QtCore.QRect(160, 200, 171, 20))
        self.lineEdit7.setText(_fromUtf8(""))
        self.lineEdit7.setObjectName(_fromUtf8("lineEdit7"))
        self.label8 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label8.setGeometry(QtCore.QRect(70, 230, 81, 16))
        self.label8.setStyleSheet(_fromUtf8(""))
        self.label8.setObjectName(_fromUtf8("label8"))
        self.lineEdit8 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit8.setGeometry(QtCore.QRect(160, 230, 171, 20))
        self.lineEdit8.setText(_fromUtf8(""))
        self.lineEdit8.setObjectName(_fromUtf8("lineEdit8"))
        self.btn_help = QtGui.QPushButton(Para_MotoType_Add_Dlg)
        self.btn_help.setGeometry(QtCore.QRect(280, 400, 75, 23))
        self.btn_help.setObjectName(_fromUtf8("btn_help"))
        self.lineEdit10 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit10.setGeometry(QtCore.QRect(160, 290, 171, 20))
        self.lineEdit10.setText(_fromUtf8(""))
        self.lineEdit10.setObjectName(_fromUtf8("lineEdit10"))
        self.label9 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label9.setGeometry(QtCore.QRect(70, 260, 81, 16))
        self.label9.setStyleSheet(_fromUtf8(""))
        self.label9.setObjectName(_fromUtf8("label9"))
        self.label10 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label10.setGeometry(QtCore.QRect(70, 290, 81, 16))
        self.label10.setStyleSheet(_fromUtf8(""))
        self.label10.setObjectName(_fromUtf8("label10"))
        self.lineEdit12 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit12.setGeometry(QtCore.QRect(160, 350, 171, 20))
        self.lineEdit12.setText(_fromUtf8(""))
        self.lineEdit12.setObjectName(_fromUtf8("lineEdit12"))
        self.lineEdit11 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit11.setGeometry(QtCore.QRect(160, 320, 171, 20))
        self.lineEdit11.setText(_fromUtf8(""))
        self.lineEdit11.setObjectName(_fromUtf8("lineEdit11"))
        self.lineEdit9 = QtGui.QLineEdit(Para_MotoType_Add_Dlg)
        self.lineEdit9.setGeometry(QtCore.QRect(160, 260, 171, 20))
        self.lineEdit9.setText(_fromUtf8(""))
        self.lineEdit9.setObjectName(_fromUtf8("lineEdit9"))
        self.label11 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label11.setGeometry(QtCore.QRect(70, 320, 81, 16))
        self.label11.setStyleSheet(_fromUtf8(""))
        self.label11.setObjectName(_fromUtf8("label11"))
        self.label12 = QtGui.QLabel(Para_MotoType_Add_Dlg)
        self.label12.setGeometry(QtCore.QRect(70, 350, 81, 16))
        self.label12.setStyleSheet(_fromUtf8(""))
        self.label12.setObjectName(_fromUtf8("label12"))

        self.retranslateUi(Para_MotoType_Add_Dlg)
        QtCore.QMetaObject.connectSlotsByName(Para_MotoType_Add_Dlg)

    def retranslateUi(self, Para_MotoType_Add_Dlg):
        Para_MotoType_Add_Dlg.setWindowTitle(_translate("Para_MotoType_Add_Dlg", "添加车型信息", None))
        self.btn_ok.setText(_translate("Para_MotoType_Add_Dlg", "确定", None))
        self.btn_cancel.setText(_translate("Para_MotoType_Add_Dlg", "取消", None))
        self.label1.setText(_translate("Para_MotoType_Add_Dlg", "车型编号*", None))
        self.label2.setText(_translate("Para_MotoType_Add_Dlg", "车型名称", None))
        self.label3.setText(_translate("Para_MotoType_Add_Dlg", "车辆类别", None))
        self.label4.setText(_translate("Para_MotoType_Add_Dlg", "驱动型式", None))
        self.label5.setText(_translate("Para_MotoType_Add_Dlg", "排放标准", None))
        self.label6.setText(_translate("Para_MotoType_Add_Dlg", "长/宽/高(mm)", None))
        self.label7.setText(_translate("Para_MotoType_Add_Dlg", "轴距(mm)", None))
        self.label8.setText(_translate("Para_MotoType_Add_Dlg", "轮距(mm)", None))
        self.btn_help.setText(_translate("Para_MotoType_Add_Dlg", "帮助", None))
        self.label9.setText(_translate("Para_MotoType_Add_Dlg", "排放标准", None))
        self.label10.setText(_translate("Para_MotoType_Add_Dlg", "长/宽/高(mm)", None))
        self.label11.setText(_translate("Para_MotoType_Add_Dlg", "轴距(mm)", None))
        self.label12.setText(_translate("Para_MotoType_Add_Dlg", "轮距(mm)", None))

