# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\freecad-8-26-all-success\Mod\Muffler\MufflerData\views\MufflerPanel_Para_2_Plan_Add.ui'
#
# Created: Fri Feb 27 10:56:45 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Para_Plan_Add_Dlg(object):
    def setupUi(self, Para_Plan_Add_Dlg):
        Para_Plan_Add_Dlg.setObjectName(_fromUtf8("Para_Plan_Add_Dlg"))
        Para_Plan_Add_Dlg.resize(474, 614)
        Para_Plan_Add_Dlg.setMinimumSize(QtCore.QSize(474, 614))
        Para_Plan_Add_Dlg.setMaximumSize(QtCore.QSize(474, 614))
        Para_Plan_Add_Dlg.setModal(False)
        self.btn_ok = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_ok.setGeometry(QtCore.QRect(80, 580, 75, 23))
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.btn_cancel = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_cancel.setGeometry(QtCore.QRect(200, 580, 75, 23))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.lineEdit1 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit1.setGeometry(QtCore.QRect(140, 10, 151, 20))
        self.lineEdit1.setText(_fromUtf8(""))
        self.lineEdit1.setObjectName(_fromUtf8("lineEdit1"))
        self.label1 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label1.setGeometry(QtCore.QRect(60, 10, 81, 16))
        self.label1.setStyleSheet(_fromUtf8(""))
        self.label1.setObjectName(_fromUtf8("label1"))
        self.label4 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label4.setGeometry(QtCore.QRect(60, 150, 71, 16))
        self.label4.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label4.setObjectName(_fromUtf8("label4"))
        self.label6 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label6.setGeometry(QtCore.QRect(60, 210, 81, 16))
        self.label6.setStyleSheet(_fromUtf8(""))
        self.label6.setObjectName(_fromUtf8("label6"))
        self.label16 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label16.setGeometry(QtCore.QRect(60, 510, 61, 16))
        self.label16.setStyleSheet(_fromUtf8(""))
        self.label16.setObjectName(_fromUtf8("label16"))
        self.lineEdit16 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit16.setGeometry(QtCore.QRect(140, 510, 151, 20))
        self.lineEdit16.setText(_fromUtf8(""))
        self.lineEdit16.setObjectName(_fromUtf8("lineEdit16"))
        self.label17 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label17.setGeometry(QtCore.QRect(60, 540, 61, 16))
        self.label17.setStyleSheet(_fromUtf8(""))
        self.label17.setObjectName(_fromUtf8("label17"))
        self.lineEdit17 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit17.setGeometry(QtCore.QRect(140, 540, 151, 20))
        self.lineEdit17.setText(_fromUtf8(""))
        self.lineEdit17.setObjectName(_fromUtf8("lineEdit17"))
        self.btn_lineEdit16 = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_lineEdit16.setGeometry(QtCore.QRect(310, 510, 61, 23))
        self.btn_lineEdit16.setObjectName(_fromUtf8("btn_lineEdit16"))
        self.btn_lineEdit17 = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_lineEdit17.setGeometry(QtCore.QRect(310, 540, 61, 23))
        self.btn_lineEdit17.setObjectName(_fromUtf8("btn_lineEdit17"))
        self.table_top = QtGui.QTableWidget(Para_Plan_Add_Dlg)
        self.table_top.setGeometry(QtCore.QRect(310, 10, 151, 251))
        self.table_top.setObjectName(_fromUtf8("table_top"))
        self.table_top.setColumnCount(1)
        self.table_top.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_top.setHorizontalHeaderItem(0, item)
        self.label2 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label2.setGeometry(QtCore.QRect(60, 40, 81, 16))
        self.label2.setStyleSheet(_fromUtf8(""))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.label3 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label3.setGeometry(QtCore.QRect(60, 90, 81, 16))
        self.label3.setStyleSheet(_fromUtf8(""))
        self.label3.setObjectName(_fromUtf8("label3"))
        self.lineEdit2 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit2.setGeometry(QtCore.QRect(140, 40, 151, 20))
        self.lineEdit2.setText(_fromUtf8(""))
        self.lineEdit2.setObjectName(_fromUtf8("lineEdit2"))
        self.lineEdit3 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit3.setGeometry(QtCore.QRect(140, 90, 151, 20))
        self.lineEdit3.setText(_fromUtf8(""))
        self.lineEdit3.setObjectName(_fromUtf8("lineEdit3"))
        self.btn_generate1 = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_generate1.setGeometry(QtCore.QRect(140, 60, 151, 23))
        self.btn_generate1.setObjectName(_fromUtf8("btn_generate1"))
        self.btn_generate2 = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_generate2.setGeometry(QtCore.QRect(140, 110, 151, 23))
        self.btn_generate2.setObjectName(_fromUtf8("btn_generate2"))
        self.label5 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label5.setGeometry(QtCore.QRect(60, 180, 71, 16))
        self.label5.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label5.setObjectName(_fromUtf8("label5"))
        self.lineEdit4 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit4.setGeometry(QtCore.QRect(140, 150, 151, 20))
        self.lineEdit4.setText(_fromUtf8(""))
        self.lineEdit4.setObjectName(_fromUtf8("lineEdit4"))
        self.lineEdit5 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit5.setGeometry(QtCore.QRect(140, 180, 151, 20))
        self.lineEdit5.setText(_fromUtf8(""))
        self.lineEdit5.setObjectName(_fromUtf8("lineEdit5"))
        self.label7 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label7.setGeometry(QtCore.QRect(60, 240, 81, 16))
        self.label7.setStyleSheet(_fromUtf8(""))
        self.label7.setObjectName(_fromUtf8("label7"))
        self.lineEdit6 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit6.setGeometry(QtCore.QRect(140, 210, 151, 20))
        self.lineEdit6.setText(_fromUtf8(""))
        self.lineEdit6.setObjectName(_fromUtf8("lineEdit6"))
        self.lineEdit7 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit7.setGeometry(QtCore.QRect(140, 240, 151, 20))
        self.lineEdit7.setText(_fromUtf8(""))
        self.lineEdit7.setObjectName(_fromUtf8("lineEdit7"))
        self.label8 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label8.setGeometry(QtCore.QRect(60, 270, 81, 16))
        self.label8.setStyleSheet(_fromUtf8(""))
        self.label8.setObjectName(_fromUtf8("label8"))
        self.lineEdit8 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit8.setGeometry(QtCore.QRect(140, 270, 151, 20))
        self.lineEdit8.setText(_fromUtf8(""))
        self.lineEdit8.setObjectName(_fromUtf8("lineEdit8"))
        self.label9 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label9.setGeometry(QtCore.QRect(60, 300, 81, 16))
        self.label9.setStyleSheet(_fromUtf8(""))
        self.label9.setObjectName(_fromUtf8("label9"))
        self.lineEdit9 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit9.setGeometry(QtCore.QRect(140, 300, 151, 20))
        self.lineEdit9.setText(_fromUtf8(""))
        self.lineEdit9.setObjectName(_fromUtf8("lineEdit9"))
        self.label10 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label10.setGeometry(QtCore.QRect(60, 330, 81, 16))
        self.label10.setStyleSheet(_fromUtf8(""))
        self.label10.setObjectName(_fromUtf8("label10"))
        self.lineEdit10 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit10.setGeometry(QtCore.QRect(140, 330, 151, 20))
        self.lineEdit10.setText(_fromUtf8(""))
        self.lineEdit10.setObjectName(_fromUtf8("lineEdit10"))
        self.label11 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label11.setGeometry(QtCore.QRect(60, 360, 81, 16))
        self.label11.setStyleSheet(_fromUtf8(""))
        self.label11.setObjectName(_fromUtf8("label11"))
        self.lineEdit11 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit11.setGeometry(QtCore.QRect(140, 360, 151, 20))
        self.lineEdit11.setText(_fromUtf8(""))
        self.lineEdit11.setObjectName(_fromUtf8("lineEdit11"))
        self.label12 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label12.setGeometry(QtCore.QRect(60, 390, 81, 16))
        self.label12.setStyleSheet(_fromUtf8(""))
        self.label12.setObjectName(_fromUtf8("label12"))
        self.lineEdit12 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit12.setGeometry(QtCore.QRect(140, 390, 151, 20))
        self.lineEdit12.setText(_fromUtf8(""))
        self.lineEdit12.setObjectName(_fromUtf8("lineEdit12"))
        self.label13 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label13.setGeometry(QtCore.QRect(60, 420, 81, 16))
        self.label13.setStyleSheet(_fromUtf8(""))
        self.label13.setObjectName(_fromUtf8("label13"))
        self.lineEdit13 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit13.setGeometry(QtCore.QRect(140, 420, 151, 20))
        self.lineEdit13.setText(_fromUtf8(""))
        self.lineEdit13.setObjectName(_fromUtf8("lineEdit13"))
        self.lineEdit14 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit14.setGeometry(QtCore.QRect(140, 450, 151, 20))
        self.lineEdit14.setText(_fromUtf8(""))
        self.lineEdit14.setObjectName(_fromUtf8("lineEdit14"))
        self.label14 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label14.setGeometry(QtCore.QRect(60, 450, 81, 16))
        self.label14.setStyleSheet(_fromUtf8(""))
        self.label14.setObjectName(_fromUtf8("label14"))
        self.label15 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label15.setGeometry(QtCore.QRect(60, 480, 81, 16))
        self.label15.setStyleSheet(_fromUtf8(""))
        self.label15.setObjectName(_fromUtf8("label15"))
        self.lineEdit15 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit15.setGeometry(QtCore.QRect(140, 480, 151, 20))
        self.lineEdit15.setText(_fromUtf8(""))
        self.lineEdit15.setObjectName(_fromUtf8("lineEdit15"))
        self.table_bottom = QtGui.QTableWidget(Para_Plan_Add_Dlg)
        self.table_bottom.setGeometry(QtCore.QRect(310, 270, 151, 231))
        self.table_bottom.setObjectName(_fromUtf8("table_bottom"))
        self.table_bottom.setColumnCount(1)
        self.table_bottom.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_bottom.setHorizontalHeaderItem(0, item)
        self.btn_help = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_help.setGeometry(QtCore.QRect(320, 580, 75, 23))
        self.btn_help.setObjectName(_fromUtf8("btn_help"))

        self.retranslateUi(Para_Plan_Add_Dlg)
        QtCore.QMetaObject.connectSlotsByName(Para_Plan_Add_Dlg)

    def retranslateUi(self, Para_Plan_Add_Dlg):
        Para_Plan_Add_Dlg.setWindowTitle(_translate("Para_Plan_Add_Dlg", "添加项目标示信息", None))
        self.btn_ok.setText(_translate("Para_Plan_Add_Dlg", "确定", None))
        self.btn_cancel.setText(_translate("Para_Plan_Add_Dlg", "取消", None))
        self.label1.setText(_translate("Para_Plan_Add_Dlg", "所属项目编号", None))
        self.label4.setText(_translate("Para_Plan_Add_Dlg", "子方案编号*", None))
        self.label6.setText(_translate("Para_Plan_Add_Dlg", "所属项目编号", None))
        self.label16.setText(_translate("Para_Plan_Add_Dlg", "SOR", None))
        self.label17.setText(_translate("Para_Plan_Add_Dlg", "GT模型", None))
        self.btn_lineEdit16.setText(_translate("Para_Plan_Add_Dlg", "浏览", None))
        self.btn_lineEdit17.setText(_translate("Para_Plan_Add_Dlg", "浏览", None))
        item = self.table_top.horizontalHeaderItem(0)
        item.setText(_translate("Para_Plan_Add_Dlg", "New Column", None))
        self.label2.setText(_translate("Para_Plan_Add_Dlg", "所属方案编号", None))
        self.label3.setText(_translate("Para_Plan_Add_Dlg", "方案标示编号", None))
        self.btn_generate1.setText(_translate("Para_Plan_Add_Dlg", "生成新的方案编号", None))
        self.btn_generate2.setText(_translate("Para_Plan_Add_Dlg", "生成子方案编号", None))
        self.label5.setText(_translate("Para_Plan_Add_Dlg", "子方案名称*", None))
        self.label7.setText(_translate("Para_Plan_Add_Dlg", "所属方案编号", None))
        self.label8.setText(_translate("Para_Plan_Add_Dlg", "排气歧管编号", None))
        self.label9.setText(_translate("Para_Plan_Add_Dlg", "催化器编号", None))
        self.label10.setText(_translate("Para_Plan_Add_Dlg", "消声器1编号", None))
        self.label11.setText(_translate("Para_Plan_Add_Dlg", "消声器2编号", None))
        self.label12.setText(_translate("Para_Plan_Add_Dlg", "消声器3编号", None))
        self.label13.setText(_translate("Para_Plan_Add_Dlg", "消声器4编号", None))
        self.label14.setText(_translate("Para_Plan_Add_Dlg", "方案设计人", None))
        self.label15.setText(_translate("Para_Plan_Add_Dlg", "录入时间", None))
        item = self.table_bottom.horizontalHeaderItem(0)
        item.setText(_translate("Para_Plan_Add_Dlg", "New Column", None))
        self.btn_help.setText(_translate("Para_Plan_Add_Dlg", "帮助", None))

