# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\freecad-8-26-all-success\Mod\Muffler\MufflerData\views\MufflerPanel_Para_2_Plan_Add.ui'
#
# Created: Tue Mar 10 16:28:17 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Para_Plan_Add_Dlg(object):
    def setupUi(self, Para_Plan_Add_Dlg):
        Para_Plan_Add_Dlg.setObjectName(_fromUtf8("Para_Plan_Add_Dlg"))
        Para_Plan_Add_Dlg.resize(439, 453)
        Para_Plan_Add_Dlg.setMinimumSize(QtCore.QSize(0, 0))
        Para_Plan_Add_Dlg.setMaximumSize(QtCore.QSize(474, 614))
        font = QtGui.QFont()
        font.setPointSize(10)
        Para_Plan_Add_Dlg.setFont(font)
        Para_Plan_Add_Dlg.setModal(False)
        self.btn_ok = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_ok.setGeometry(QtCore.QRect(40, 400, 75, 23))
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.btn_cancel = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_cancel.setGeometry(QtCore.QRect(170, 400, 75, 23))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.label4 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label4.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label4.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label4.setObjectName(_fromUtf8("label4"))
        self.label16 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label16.setGeometry(QtCore.QRect(20, 330, 61, 16))
        self.label16.setStyleSheet(_fromUtf8(""))
        self.label16.setObjectName(_fromUtf8("label16"))
        self.lineEdit16 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit16.setGeometry(QtCore.QRect(100, 30, 250, 20))
        self.lineEdit16.setText(_fromUtf8(""))
        self.lineEdit16.setObjectName(_fromUtf8("lineEdit16"))
        self.label17 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label17.setGeometry(QtCore.QRect(20, 360, 61, 16))
        self.label17.setStyleSheet(_fromUtf8(""))
        self.label17.setObjectName(_fromUtf8("label17"))
        self.lineEdit17 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit17.setGeometry(QtCore.QRect(100, 60, 250, 20))
        self.lineEdit17.setText(_fromUtf8(""))
        self.lineEdit17.setObjectName(_fromUtf8("lineEdit17"))
        self.btn_lineEdit16 = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_lineEdit16.setGeometry(QtCore.QRect(360, 330, 61, 23))
        self.btn_lineEdit16.setObjectName(_fromUtf8("btn_lineEdit16"))
        self.btn_lineEdit17 = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_lineEdit17.setGeometry(QtCore.QRect(360, 360, 61, 23))
        self.btn_lineEdit17.setObjectName(_fromUtf8("btn_lineEdit17"))
        self.label5 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label5.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label5.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label5.setObjectName(_fromUtf8("label5"))
        self.lineEdit5 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit5.setGeometry(QtCore.QRect(100, 90, 250, 20))
        self.lineEdit5.setText(_fromUtf8(""))
        self.lineEdit5.setObjectName(_fromUtf8("lineEdit5"))
        self.label7 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label7.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label7.setStyleSheet(_fromUtf8(""))
        self.label7.setObjectName(_fromUtf8("label7"))
        self.lineEdit6 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit6.setGeometry(QtCore.QRect(100, 120, 250, 20))
        self.lineEdit6.setText(_fromUtf8(""))
        self.lineEdit6.setObjectName(_fromUtf8("lineEdit6"))
        self.lineEdit7 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit7.setGeometry(QtCore.QRect(100, 150, 250, 20))
        self.lineEdit7.setText(_fromUtf8(""))
        self.lineEdit7.setObjectName(_fromUtf8("lineEdit7"))
        self.label8 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label8.setGeometry(QtCore.QRect(20, 120, 81, 16))
        self.label8.setStyleSheet(_fromUtf8(""))
        self.label8.setObjectName(_fromUtf8("label8"))
        self.lineEdit8 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit8.setGeometry(QtCore.QRect(100, 180, 250, 20))
        self.lineEdit8.setText(_fromUtf8(""))
        self.lineEdit8.setObjectName(_fromUtf8("lineEdit8"))
        self.label9 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label9.setGeometry(QtCore.QRect(20, 150, 81, 16))
        self.label9.setStyleSheet(_fromUtf8(""))
        self.label9.setObjectName(_fromUtf8("label9"))
        self.lineEdit9 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit9.setGeometry(QtCore.QRect(100, 210, 250, 20))
        self.lineEdit9.setText(_fromUtf8(""))
        self.lineEdit9.setObjectName(_fromUtf8("lineEdit9"))
        self.label10 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label10.setGeometry(QtCore.QRect(20, 180, 81, 16))
        self.label10.setStyleSheet(_fromUtf8(""))
        self.label10.setObjectName(_fromUtf8("label10"))
        self.lineEdit10 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit10.setGeometry(QtCore.QRect(100, 240, 250, 20))
        self.lineEdit10.setText(_fromUtf8(""))
        self.lineEdit10.setObjectName(_fromUtf8("lineEdit10"))
        self.label11 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label11.setGeometry(QtCore.QRect(20, 210, 81, 16))
        self.label11.setStyleSheet(_fromUtf8(""))
        self.label11.setObjectName(_fromUtf8("label11"))
        self.lineEdit11 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit11.setGeometry(QtCore.QRect(100, 270, 250, 20))
        self.lineEdit11.setText(_fromUtf8(""))
        self.lineEdit11.setObjectName(_fromUtf8("lineEdit11"))
        self.label12 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label12.setGeometry(QtCore.QRect(20, 240, 81, 16))
        self.label12.setStyleSheet(_fromUtf8(""))
        self.label12.setObjectName(_fromUtf8("label12"))
        self.lineEdit12 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit12.setGeometry(QtCore.QRect(100, 300, 250, 20))
        self.lineEdit12.setText(_fromUtf8(""))
        self.lineEdit12.setObjectName(_fromUtf8("lineEdit12"))
        self.label13 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label13.setGeometry(QtCore.QRect(20, 270, 81, 16))
        self.label13.setStyleSheet(_fromUtf8(""))
        self.label13.setObjectName(_fromUtf8("label13"))
        self.lineEdit14 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit14.setGeometry(QtCore.QRect(100, 330, 250, 20))
        self.lineEdit14.setText(_fromUtf8(""))
        self.lineEdit14.setObjectName(_fromUtf8("lineEdit14"))
        self.label14 = QtGui.QLabel(Para_Plan_Add_Dlg)
        self.label14.setGeometry(QtCore.QRect(20, 300, 81, 16))
        self.label14.setStyleSheet(_fromUtf8(""))
        self.label14.setObjectName(_fromUtf8("label14"))
        self.lineEdit15 = QtGui.QLineEdit(Para_Plan_Add_Dlg)
        self.lineEdit15.setGeometry(QtCore.QRect(100, 360, 250, 20))
        self.lineEdit15.setText(_fromUtf8(""))
        self.lineEdit15.setObjectName(_fromUtf8("lineEdit15"))
        self.btn_help = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_help.setGeometry(QtCore.QRect(300, 400, 75, 23))
        self.btn_help.setObjectName(_fromUtf8("btn_help"))
        self.btn_generate1 = QtGui.QPushButton(Para_Plan_Add_Dlg)
        self.btn_generate1.setGeometry(QtCore.QRect(360, 30, 61, 23))
        self.btn_generate1.setObjectName(_fromUtf8("btn_generate1"))

        self.retranslateUi(Para_Plan_Add_Dlg)
        QtCore.QMetaObject.connectSlotsByName(Para_Plan_Add_Dlg)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit16, self.lineEdit17)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit17, self.lineEdit5)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit5, self.lineEdit6)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit6, self.lineEdit7)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit7, self.lineEdit8)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit8, self.lineEdit9)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit9, self.lineEdit10)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit10, self.lineEdit11)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit11, self.lineEdit12)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit12, self.lineEdit14)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit14, self.lineEdit15)
        Para_Plan_Add_Dlg.setTabOrder(self.lineEdit15, self.btn_ok)
        Para_Plan_Add_Dlg.setTabOrder(self.btn_ok, self.btn_cancel)
        Para_Plan_Add_Dlg.setTabOrder(self.btn_cancel, self.btn_help)
        Para_Plan_Add_Dlg.setTabOrder(self.btn_help, self.btn_generate1)
        Para_Plan_Add_Dlg.setTabOrder(self.btn_generate1, self.btn_lineEdit16)
        Para_Plan_Add_Dlg.setTabOrder(self.btn_lineEdit16, self.btn_lineEdit17)

    def retranslateUi(self, Para_Plan_Add_Dlg):
        Para_Plan_Add_Dlg.setWindowTitle(_translate("Para_Plan_Add_Dlg", "添加子方案信息", None))
        self.btn_ok.setText(_translate("Para_Plan_Add_Dlg", "确定", None))
        self.btn_cancel.setText(_translate("Para_Plan_Add_Dlg", "取消", None))
        self.label4.setText(_translate("Para_Plan_Add_Dlg", "子方案编号*", None))
        self.label16.setText(_translate("Para_Plan_Add_Dlg", "测试结果", None))
        self.label17.setText(_translate("Para_Plan_Add_Dlg", "分析结果", None))
        self.btn_lineEdit16.setText(_translate("Para_Plan_Add_Dlg", "浏览", None))
        self.btn_lineEdit17.setText(_translate("Para_Plan_Add_Dlg", "浏览", None))
        self.label5.setText(_translate("Para_Plan_Add_Dlg", "子方案名称*", None))
        self.label7.setText(_translate("Para_Plan_Add_Dlg", "所属方案编号", None))
        self.label8.setText(_translate("Para_Plan_Add_Dlg", "排气歧管编号", None))
        self.label9.setText(_translate("Para_Plan_Add_Dlg", "催化器编号", None))
        self.label10.setText(_translate("Para_Plan_Add_Dlg", "消声器1编号", None))
        self.label11.setText(_translate("Para_Plan_Add_Dlg", "消声器2编号", None))
        self.label12.setText(_translate("Para_Plan_Add_Dlg", "消声器3编号", None))
        self.label13.setText(_translate("Para_Plan_Add_Dlg", "消声器4编号", None))
        self.lineEdit14.setToolTip(_translate("Para_Plan_Add_Dlg", "lineFiles", None))
        self.label14.setText(_translate("Para_Plan_Add_Dlg", "方案设计人", None))
        self.lineEdit15.setToolTip(_translate("Para_Plan_Add_Dlg", "lineFiles", None))
        self.btn_help.setText(_translate("Para_Plan_Add_Dlg", "帮助", None))
        self.btn_generate1.setText(_translate("Para_Plan_Add_Dlg", "生成", None))

