# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\freecad-8-26-all-success\Mod\Database\MufflerData\views\MufflerPanel_Para_5_Engine_Add.ui'
#
# Created: Wed Feb 25 11:23:35 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Para_Engine_Add_Dlg(object):
    def setupUi(self, Para_Engine_Add_Dlg):
        Para_Engine_Add_Dlg.setObjectName(_fromUtf8("Para_Engine_Add_Dlg"))
        Para_Engine_Add_Dlg.resize(916, 450)
        Para_Engine_Add_Dlg.setMinimumSize(QtCore.QSize(916, 450))
        Para_Engine_Add_Dlg.setMaximumSize(QtCore.QSize(916, 450))
        Para_Engine_Add_Dlg.setModal(False)
        self.lineEdit1 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit1.setEnabled(False)
        self.lineEdit1.setGeometry(QtCore.QRect(130, 30, 141, 20))
        self.lineEdit1.setObjectName(_fromUtf8("lineEdit1"))
        self.btn_ok = QtGui.QPushButton(Para_Engine_Add_Dlg)
        self.btn_ok.setGeometry(QtCore.QRect(320, 400, 75, 23))
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.btn_cancel = QtGui.QPushButton(Para_Engine_Add_Dlg)
        self.btn_cancel.setGeometry(QtCore.QRect(440, 400, 75, 23))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.label1 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label1.setGeometry(QtCore.QRect(40, 30, 81, 16))
        self.label1.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label1.setObjectName(_fromUtf8("label1"))
        self.lineEdit2 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit2.setGeometry(QtCore.QRect(130, 70, 141, 20))
        self.lineEdit2.setText(_fromUtf8(""))
        self.lineEdit2.setObjectName(_fromUtf8("lineEdit2"))
        self.label2 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label2.setGeometry(QtCore.QRect(40, 70, 81, 16))
        self.label2.setStyleSheet(_fromUtf8(""))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.lineEdit3 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit3.setGeometry(QtCore.QRect(130, 110, 141, 20))
        self.lineEdit3.setText(_fromUtf8(""))
        self.lineEdit3.setObjectName(_fromUtf8("lineEdit3"))
        self.label3 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label3.setGeometry(QtCore.QRect(40, 110, 81, 16))
        self.label3.setStyleSheet(_fromUtf8(""))
        self.label3.setObjectName(_fromUtf8("label3"))
        self.label4 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label4.setGeometry(QtCore.QRect(40, 150, 81, 16))
        self.label4.setStyleSheet(_fromUtf8(""))
        self.label4.setObjectName(_fromUtf8("label4"))
        self.lineEdit4 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit4.setGeometry(QtCore.QRect(130, 150, 141, 20))
        self.lineEdit4.setText(_fromUtf8(""))
        self.lineEdit4.setObjectName(_fromUtf8("lineEdit4"))
        self.label5 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label5.setGeometry(QtCore.QRect(40, 190, 81, 16))
        self.label5.setStyleSheet(_fromUtf8(""))
        self.label5.setObjectName(_fromUtf8("label5"))
        self.lineEdit5 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit5.setGeometry(QtCore.QRect(130, 190, 141, 20))
        self.lineEdit5.setText(_fromUtf8(""))
        self.lineEdit5.setObjectName(_fromUtf8("lineEdit5"))
        self.label6 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label6.setGeometry(QtCore.QRect(40, 230, 81, 16))
        self.label6.setStyleSheet(_fromUtf8(""))
        self.label6.setObjectName(_fromUtf8("label6"))
        self.lineEdit6 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit6.setGeometry(QtCore.QRect(130, 230, 141, 20))
        self.lineEdit6.setText(_fromUtf8(""))
        self.lineEdit6.setObjectName(_fromUtf8("lineEdit6"))
        self.label7 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label7.setGeometry(QtCore.QRect(40, 270, 81, 16))
        self.label7.setStyleSheet(_fromUtf8(""))
        self.label7.setObjectName(_fromUtf8("label7"))
        self.lineEdit7 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit7.setGeometry(QtCore.QRect(130, 270, 141, 20))
        self.lineEdit7.setText(_fromUtf8(""))
        self.lineEdit7.setObjectName(_fromUtf8("lineEdit7"))
        self.label8 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label8.setGeometry(QtCore.QRect(40, 310, 81, 16))
        self.label8.setStyleSheet(_fromUtf8(""))
        self.label8.setObjectName(_fromUtf8("label8"))
        self.lineEdit8 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit8.setGeometry(QtCore.QRect(130, 310, 141, 20))
        self.lineEdit8.setText(_fromUtf8(""))
        self.lineEdit8.setObjectName(_fromUtf8("lineEdit8"))
        self.btn_help = QtGui.QPushButton(Para_Engine_Add_Dlg)
        self.btn_help.setGeometry(QtCore.QRect(560, 400, 75, 23))
        self.btn_help.setObjectName(_fromUtf8("btn_help"))
        self.label9 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label9.setGeometry(QtCore.QRect(40, 350, 81, 16))
        self.label9.setStyleSheet(_fromUtf8(""))
        self.label9.setObjectName(_fromUtf8("label9"))
        self.lineEdit9 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit9.setGeometry(QtCore.QRect(130, 350, 141, 20))
        self.lineEdit9.setText(_fromUtf8(""))
        self.lineEdit9.setObjectName(_fromUtf8("lineEdit9"))
        self.lineEdit14 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit14.setGeometry(QtCore.QRect(430, 190, 151, 20))
        self.lineEdit14.setText(_fromUtf8(""))
        self.lineEdit14.setObjectName(_fromUtf8("lineEdit14"))
        self.label14 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label14.setGeometry(QtCore.QRect(290, 190, 81, 16))
        self.label14.setStyleSheet(_fromUtf8(""))
        self.label14.setObjectName(_fromUtf8("label14"))
        self.label17 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label17.setGeometry(QtCore.QRect(290, 310, 141, 21))
        self.label17.setStyleSheet(_fromUtf8(""))
        self.label17.setObjectName(_fromUtf8("label17"))
        self.label11 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label11.setGeometry(QtCore.QRect(290, 70, 81, 16))
        self.label11.setStyleSheet(_fromUtf8(""))
        self.label11.setObjectName(_fromUtf8("label11"))
        self.label16 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label16.setGeometry(QtCore.QRect(290, 270, 101, 16))
        self.label16.setStyleSheet(_fromUtf8(""))
        self.label16.setObjectName(_fromUtf8("label16"))
        self.label12 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label12.setGeometry(QtCore.QRect(290, 110, 81, 16))
        self.label12.setStyleSheet(_fromUtf8(""))
        self.label12.setObjectName(_fromUtf8("label12"))
        self.lineEdit13 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit13.setGeometry(QtCore.QRect(430, 150, 151, 20))
        self.lineEdit13.setText(_fromUtf8(""))
        self.lineEdit13.setObjectName(_fromUtf8("lineEdit13"))
        self.label18 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label18.setGeometry(QtCore.QRect(290, 350, 131, 16))
        self.label18.setStyleSheet(_fromUtf8(""))
        self.label18.setObjectName(_fromUtf8("label18"))
        self.label13 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label13.setGeometry(QtCore.QRect(290, 150, 91, 16))
        self.label13.setStyleSheet(_fromUtf8(""))
        self.label13.setObjectName(_fromUtf8("label13"))
        self.lineEdit12 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit12.setGeometry(QtCore.QRect(430, 110, 151, 20))
        self.lineEdit12.setText(_fromUtf8(""))
        self.lineEdit12.setObjectName(_fromUtf8("lineEdit12"))
        self.lineEdit16 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit16.setGeometry(QtCore.QRect(430, 270, 151, 20))
        self.lineEdit16.setText(_fromUtf8(""))
        self.lineEdit16.setObjectName(_fromUtf8("lineEdit16"))
        self.label15 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label15.setGeometry(QtCore.QRect(290, 230, 81, 16))
        self.label15.setStyleSheet(_fromUtf8(""))
        self.label15.setObjectName(_fromUtf8("label15"))
        self.lineEdit17 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit17.setGeometry(QtCore.QRect(430, 310, 151, 20))
        self.lineEdit17.setText(_fromUtf8(""))
        self.lineEdit17.setObjectName(_fromUtf8("lineEdit17"))
        self.lineEdit15 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit15.setGeometry(QtCore.QRect(430, 230, 151, 20))
        self.lineEdit15.setText(_fromUtf8(""))
        self.lineEdit15.setObjectName(_fromUtf8("lineEdit15"))
        self.lineEdit18 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit18.setGeometry(QtCore.QRect(430, 350, 151, 20))
        self.lineEdit18.setText(_fromUtf8(""))
        self.lineEdit18.setObjectName(_fromUtf8("lineEdit18"))
        self.lineEdit11 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit11.setGeometry(QtCore.QRect(430, 70, 151, 20))
        self.lineEdit11.setText(_fromUtf8(""))
        self.lineEdit11.setObjectName(_fromUtf8("lineEdit11"))
        self.lineEdit23 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit23.setGeometry(QtCore.QRect(750, 190, 141, 20))
        self.lineEdit23.setText(_fromUtf8(""))
        self.lineEdit23.setObjectName(_fromUtf8("lineEdit23"))
        self.label23 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label23.setGeometry(QtCore.QRect(600, 190, 81, 16))
        self.label23.setStyleSheet(_fromUtf8(""))
        self.label23.setObjectName(_fromUtf8("label23"))
        self.label26 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label26.setGeometry(QtCore.QRect(600, 310, 81, 16))
        self.label26.setStyleSheet(_fromUtf8(""))
        self.label26.setObjectName(_fromUtf8("label26"))
        self.label20 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label20.setGeometry(QtCore.QRect(600, 70, 101, 16))
        self.label20.setStyleSheet(_fromUtf8(""))
        self.label20.setObjectName(_fromUtf8("label20"))
        self.label25 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label25.setGeometry(QtCore.QRect(600, 270, 81, 16))
        self.label25.setStyleSheet(_fromUtf8(""))
        self.label25.setObjectName(_fromUtf8("label25"))
        self.label21 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label21.setGeometry(QtCore.QRect(600, 110, 101, 16))
        self.label21.setStyleSheet(_fromUtf8(""))
        self.label21.setObjectName(_fromUtf8("label21"))
        self.lineEdit22 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit22.setGeometry(QtCore.QRect(750, 150, 141, 20))
        self.lineEdit22.setText(_fromUtf8(""))
        self.lineEdit22.setObjectName(_fromUtf8("lineEdit22"))
        self.label27 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label27.setGeometry(QtCore.QRect(600, 350, 81, 16))
        self.label27.setStyleSheet(_fromUtf8(""))
        self.label27.setObjectName(_fromUtf8("label27"))
        self.label22 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label22.setGeometry(QtCore.QRect(600, 150, 101, 16))
        self.label22.setStyleSheet(_fromUtf8(""))
        self.label22.setObjectName(_fromUtf8("label22"))
        self.lineEdit21 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit21.setGeometry(QtCore.QRect(750, 110, 141, 20))
        self.lineEdit21.setText(_fromUtf8(""))
        self.lineEdit21.setObjectName(_fromUtf8("lineEdit21"))
        self.lineEdit25 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit25.setGeometry(QtCore.QRect(750, 270, 141, 20))
        self.lineEdit25.setText(_fromUtf8(""))
        self.lineEdit25.setObjectName(_fromUtf8("lineEdit25"))
        self.label24 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label24.setGeometry(QtCore.QRect(600, 230, 81, 16))
        self.label24.setStyleSheet(_fromUtf8(""))
        self.label24.setObjectName(_fromUtf8("label24"))
        self.lineEdit26 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit26.setGeometry(QtCore.QRect(750, 310, 141, 20))
        self.lineEdit26.setText(_fromUtf8(""))
        self.lineEdit26.setObjectName(_fromUtf8("lineEdit26"))
        self.lineEdit24 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit24.setGeometry(QtCore.QRect(750, 230, 141, 20))
        self.lineEdit24.setText(_fromUtf8(""))
        self.lineEdit24.setObjectName(_fromUtf8("lineEdit24"))
        self.lineEdit27 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit27.setGeometry(QtCore.QRect(750, 350, 141, 20))
        self.lineEdit27.setText(_fromUtf8(""))
        self.lineEdit27.setObjectName(_fromUtf8("lineEdit27"))
        self.lineEdit20 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit20.setGeometry(QtCore.QRect(750, 70, 141, 20))
        self.lineEdit20.setText(_fromUtf8(""))
        self.lineEdit20.setObjectName(_fromUtf8("lineEdit20"))
        self.lineEdit10 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit10.setGeometry(QtCore.QRect(430, 30, 151, 20))
        self.lineEdit10.setText(_fromUtf8(""))
        self.lineEdit10.setObjectName(_fromUtf8("lineEdit10"))
        self.label10 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label10.setGeometry(QtCore.QRect(290, 30, 81, 16))
        self.label10.setStyleSheet(_fromUtf8(""))
        self.label10.setObjectName(_fromUtf8("label10"))
        self.lineEdit19 = QtGui.QLineEdit(Para_Engine_Add_Dlg)
        self.lineEdit19.setGeometry(QtCore.QRect(750, 30, 141, 20))
        self.lineEdit19.setText(_fromUtf8(""))
        self.lineEdit19.setObjectName(_fromUtf8("lineEdit19"))
        self.label19 = QtGui.QLabel(Para_Engine_Add_Dlg)
        self.label19.setGeometry(QtCore.QRect(600, 30, 141, 16))
        self.label19.setStyleSheet(_fromUtf8(""))
        self.label19.setObjectName(_fromUtf8("label19"))

        self.retranslateUi(Para_Engine_Add_Dlg)
        QtCore.QMetaObject.connectSlotsByName(Para_Engine_Add_Dlg)

    def retranslateUi(self, Para_Engine_Add_Dlg):
        Para_Engine_Add_Dlg.setWindowTitle(_translate("Para_Engine_Add_Dlg", "添加发动机信息", None))
        self.btn_ok.setText(_translate("Para_Engine_Add_Dlg", "确定", None))
        self.btn_cancel.setText(_translate("Para_Engine_Add_Dlg", "取消", None))
        self.label1.setText(_translate("Para_Engine_Add_Dlg", "发动机型号*", None))
        self.label2.setText(_translate("Para_Engine_Add_Dlg", "发动机排量(L)", None))
        self.label3.setText(_translate("Para_Engine_Add_Dlg", "活塞行程(mm)", None))
        self.label4.setText(_translate("Para_Engine_Add_Dlg", "气缸直径(mm)", None))
        self.label5.setText(_translate("Para_Engine_Add_Dlg", "气缸个数(个)", None))
        self.label6.setText(_translate("Para_Engine_Add_Dlg", "气缸排列方式", None))
        self.label7.setText(_translate("Para_Engine_Add_Dlg", "吸气方式", None))
        self.label8.setText(_translate("Para_Engine_Add_Dlg", "配气方式", None))
        self.btn_help.setText(_translate("Para_Engine_Add_Dlg", "帮助", None))
        self.label9.setText(_translate("Para_Engine_Add_Dlg", "增压方式", None))
        self.label14.setText(_translate("Para_Engine_Add_Dlg", "最大功率(KW)", None))
        self.label17.setText(_translate("Para_Engine_Add_Dlg", "最高气体温度下转速(rpm)", None))
        self.label11.setText(_translate("Para_Engine_Add_Dlg", "压缩比", None))
        self.label16.setText(_translate("Para_Engine_Add_Dlg", "最高气体温度(`C)", None))
        self.label12.setText(_translate("Para_Engine_Add_Dlg", "标定转速(rpm)", None))
        self.label18.setText(_translate("Para_Engine_Add_Dlg", "最大气流质量流量(g/s)", None))
        self.label13.setText(_translate("Para_Engine_Add_Dlg", "怠速时转速(rpm)", None))
        self.label15.setText(_translate("Para_Engine_Add_Dlg", "最大扭矩(Nm)", None))
        self.label23.setText(_translate("Para_Engine_Add_Dlg", "EGR", None))
        self.label26.setText(_translate("Para_Engine_Add_Dlg", "厂家电话", None))
        self.label20.setText(_translate("Para_Engine_Add_Dlg", "最低油耗点(rpm)", None))
        self.label25.setText(_translate("Para_Engine_Add_Dlg", "厂家地址", None))
        self.label21.setText(_translate("Para_Engine_Add_Dlg", "最大扭矩点(rpm)", None))
        self.label27.setText(_translate("Para_Engine_Add_Dlg", "厂家电子邮箱", None))
        self.label22.setText(_translate("Para_Engine_Add_Dlg", "最大功率点(rpm)", None))
        self.label24.setText(_translate("Para_Engine_Add_Dlg", "生产厂家名称", None))
        self.label10.setText(_translate("Para_Engine_Add_Dlg", "冷却方式", None))
        self.label19.setText(_translate("Para_Engine_Add_Dlg", "最大气流流量下转速(rpm)", None))

