# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\freecad-8-26-all-success\Mod\Muffler\MufflerData\views\MufflerPanel_Para_1_Project_Add.ui'
#
# Created: Tue Mar 10 16:28:17 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Para_Project_Add_Dlg(object):
    def setupUi(self, Para_Project_Add_Dlg):
        Para_Project_Add_Dlg.setObjectName(_fromUtf8("Para_Project_Add_Dlg"))
        Para_Project_Add_Dlg.resize(499, 459)
        Para_Project_Add_Dlg.setMinimumSize(QtCore.QSize(499, 459))
        Para_Project_Add_Dlg.setMaximumSize(QtCore.QSize(499, 459))
        Para_Project_Add_Dlg.setModal(False)
        self.lineEdit1 = QtGui.QLineEdit(Para_Project_Add_Dlg)
        self.lineEdit1.setEnabled(True)
        self.lineEdit1.setGeometry(QtCore.QRect(130, 30, 221, 20))
        self.lineEdit1.setObjectName(_fromUtf8("lineEdit1"))
        self.btn_ok = QtGui.QPushButton(Para_Project_Add_Dlg)
        self.btn_ok.setGeometry(QtCore.QRect(100, 410, 75, 23))
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.btn_cancel = QtGui.QPushButton(Para_Project_Add_Dlg)
        self.btn_cancel.setGeometry(QtCore.QRect(220, 410, 75, 23))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.label1 = QtGui.QLabel(Para_Project_Add_Dlg)
        self.label1.setGeometry(QtCore.QRect(60, 30, 61, 16))
        self.label1.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label1.setObjectName(_fromUtf8("label1"))
        self.lineEdit2 = QtGui.QLineEdit(Para_Project_Add_Dlg)
        self.lineEdit2.setGeometry(QtCore.QRect(130, 70, 221, 20))
        self.lineEdit2.setObjectName(_fromUtf8("lineEdit2"))
        self.label2 = QtGui.QLabel(Para_Project_Add_Dlg)
        self.label2.setGeometry(QtCore.QRect(60, 70, 61, 16))
        self.label2.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.lineEdit3 = QtGui.QLineEdit(Para_Project_Add_Dlg)
        self.lineEdit3.setGeometry(QtCore.QRect(130, 110, 221, 20))
        self.lineEdit3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit3.setText(_fromUtf8(""))
        self.lineEdit3.setObjectName(_fromUtf8("lineEdit3"))
        self.label3 = QtGui.QLabel(Para_Project_Add_Dlg)
        self.label3.setGeometry(QtCore.QRect(60, 110, 61, 16))
        self.label3.setStyleSheet(_fromUtf8(""))
        self.label3.setObjectName(_fromUtf8("label3"))
        self.lineEdit4 = QtGui.QLineEdit(Para_Project_Add_Dlg)
        self.lineEdit4.setGeometry(QtCore.QRect(130, 150, 221, 20))
        self.lineEdit4.setText(_fromUtf8(""))
        self.lineEdit4.setObjectName(_fromUtf8("lineEdit4"))
        self.label4 = QtGui.QLabel(Para_Project_Add_Dlg)
        self.label4.setGeometry(QtCore.QRect(60, 150, 61, 16))
        self.label4.setStyleSheet(_fromUtf8(""))
        self.label4.setObjectName(_fromUtf8("label4"))
        self.label5 = QtGui.QLabel(Para_Project_Add_Dlg)
        self.label5.setGeometry(QtCore.QRect(60, 190, 61, 16))
        self.label5.setStyleSheet(_fromUtf8(""))
        self.label5.setObjectName(_fromUtf8("label5"))
        self.lineEdit5 = QtGui.QLineEdit(Para_Project_Add_Dlg)
        self.lineEdit5.setGeometry(QtCore.QRect(130, 190, 221, 20))
        self.lineEdit5.setText(_fromUtf8(""))
        self.lineEdit5.setObjectName(_fromUtf8("lineEdit5"))
        self.label7 = QtGui.QLabel(Para_Project_Add_Dlg)
        self.label7.setGeometry(QtCore.QRect(60, 270, 61, 16))
        self.label7.setStyleSheet(_fromUtf8(""))
        self.label7.setObjectName(_fromUtf8("label7"))
        self.lineEdit6 = QtGui.QLineEdit(Para_Project_Add_Dlg)
        self.lineEdit6.setEnabled(False)
        self.lineEdit6.setGeometry(QtCore.QRect(130, 230, 221, 20))
        self.lineEdit6.setText(_fromUtf8(""))
        self.lineEdit6.setObjectName(_fromUtf8("lineEdit6"))
        self.label8 = QtGui.QLabel(Para_Project_Add_Dlg)
        self.label8.setGeometry(QtCore.QRect(60, 310, 61, 16))
        self.label8.setStyleSheet(_fromUtf8(""))
        self.label8.setObjectName(_fromUtf8("label8"))
        self.lineEdit7 = QtGui.QLineEdit(Para_Project_Add_Dlg)
        self.lineEdit7.setEnabled(False)
        self.lineEdit7.setGeometry(QtCore.QRect(130, 270, 221, 20))
        self.lineEdit7.setText(_fromUtf8(""))
        self.lineEdit7.setObjectName(_fromUtf8("lineEdit7"))
        self.label9 = QtGui.QLabel(Para_Project_Add_Dlg)
        self.label9.setGeometry(QtCore.QRect(60, 350, 61, 16))
        self.label9.setStyleSheet(_fromUtf8(""))
        self.label9.setObjectName(_fromUtf8("label9"))
        self.lineEdit8 = QtGui.QLineEdit(Para_Project_Add_Dlg)
        self.lineEdit8.setGeometry(QtCore.QRect(130, 310, 221, 20))
        self.lineEdit8.setText(_fromUtf8(""))
        self.lineEdit8.setObjectName(_fromUtf8("lineEdit8"))
        self.btn_lineEdit8 = QtGui.QPushButton(Para_Project_Add_Dlg)
        self.btn_lineEdit8.setGeometry(QtCore.QRect(380, 310, 61, 23))
        self.btn_lineEdit8.setObjectName(_fromUtf8("btn_lineEdit8"))
        self.btn_lineEdit9 = QtGui.QPushButton(Para_Project_Add_Dlg)
        self.btn_lineEdit9.setGeometry(QtCore.QRect(380, 350, 61, 23))
        self.btn_lineEdit9.setObjectName(_fromUtf8("btn_lineEdit9"))
        self.btn_help = QtGui.QPushButton(Para_Project_Add_Dlg)
        self.btn_help.setGeometry(QtCore.QRect(340, 410, 75, 23))
        self.btn_help.setObjectName(_fromUtf8("btn_help"))
        self.btn_generate = QtGui.QPushButton(Para_Project_Add_Dlg)
        self.btn_generate.setGeometry(QtCore.QRect(380, 30, 61, 23))
        self.btn_generate.setObjectName(_fromUtf8("btn_generate"))
        self.lineEdit9 = QtGui.QLineEdit(Para_Project_Add_Dlg)
        self.lineEdit9.setEnabled(True)
        self.lineEdit9.setGeometry(QtCore.QRect(130, 350, 221, 20))
        self.lineEdit9.setText(_fromUtf8(""))
        self.lineEdit9.setObjectName(_fromUtf8("lineEdit9"))
        self.label7_2 = QtGui.QLabel(Para_Project_Add_Dlg)
        self.label7_2.setGeometry(QtCore.QRect(60, 230, 61, 16))
        self.label7_2.setStyleSheet(_fromUtf8(""))
        self.label7_2.setObjectName(_fromUtf8("label7_2"))

        self.retranslateUi(Para_Project_Add_Dlg)
        QtCore.QMetaObject.connectSlotsByName(Para_Project_Add_Dlg)
        Para_Project_Add_Dlg.setTabOrder(self.lineEdit1, self.lineEdit2)
        Para_Project_Add_Dlg.setTabOrder(self.lineEdit2, self.lineEdit3)
        Para_Project_Add_Dlg.setTabOrder(self.lineEdit3, self.lineEdit4)
        Para_Project_Add_Dlg.setTabOrder(self.lineEdit4, self.lineEdit5)
        Para_Project_Add_Dlg.setTabOrder(self.lineEdit5, self.lineEdit6)
        Para_Project_Add_Dlg.setTabOrder(self.lineEdit6, self.lineEdit7)
        Para_Project_Add_Dlg.setTabOrder(self.lineEdit7, self.lineEdit8)
        Para_Project_Add_Dlg.setTabOrder(self.lineEdit8, self.btn_ok)
        Para_Project_Add_Dlg.setTabOrder(self.btn_ok, self.btn_cancel)
        Para_Project_Add_Dlg.setTabOrder(self.btn_cancel, self.btn_help)
        Para_Project_Add_Dlg.setTabOrder(self.btn_help, self.btn_generate)
        Para_Project_Add_Dlg.setTabOrder(self.btn_generate, self.btn_lineEdit8)
        Para_Project_Add_Dlg.setTabOrder(self.btn_lineEdit8, self.btn_lineEdit9)

    def retranslateUi(self, Para_Project_Add_Dlg):
        Para_Project_Add_Dlg.setWindowTitle(_translate("Para_Project_Add_Dlg", "项目信息录入", None))
        self.btn_ok.setText(_translate("Para_Project_Add_Dlg", "确定", None))
        self.btn_cancel.setText(_translate("Para_Project_Add_Dlg", "取消", None))
        self.label1.setText(_translate("Para_Project_Add_Dlg", "项目编号*", None))
        self.label2.setText(_translate("Para_Project_Add_Dlg", "项目名称*", None))
        self.label3.setText(_translate("Para_Project_Add_Dlg", "车型编号", None))
        self.label4.setText(_translate("Para_Project_Add_Dlg", "发动机型号", None))
        self.label5.setText(_translate("Para_Project_Add_Dlg", "项目负责人", None))
        self.label7.setText(_translate("Para_Project_Add_Dlg", "录入时间", None))
        self.label8.setText(_translate("Para_Project_Add_Dlg", "SOR", None))
        self.label9.setText(_translate("Para_Project_Add_Dlg", "GT模型", None))
        self.lineEdit8.setToolTip(_translate("Para_Project_Add_Dlg", "lineFiles", None))
        self.btn_lineEdit8.setText(_translate("Para_Project_Add_Dlg", "浏览", None))
        self.btn_lineEdit9.setText(_translate("Para_Project_Add_Dlg", "浏览", None))
        self.btn_help.setText(_translate("Para_Project_Add_Dlg", "帮助", None))
        self.btn_generate.setText(_translate("Para_Project_Add_Dlg", "生成", None))
        self.lineEdit9.setToolTip(_translate("Para_Project_Add_Dlg", "lineFiles", None))
        self.label7_2.setText(_translate("Para_Project_Add_Dlg", "录入人", None))

